### ISSUE TITLE
Not able to build

### ISSUE THREAD

**Issue by tonyhayes** [staticdesigner/modevue#5]
I am using the latest version of the vue cli

Tonys-MacBook-Pro:trisha tony.hayes$ vue --version
@vue/cli 4.2.3

I have run npm install
npm run dev

and I get the following cli error

Tonys-MacBook-Pro:trisha tony.hayes$ npm run dev

> trish@1.0.0 dev /Users/tony.hayes/git/trisha
> nuxt

/Users/tony.hayes/git/trisha/node_modules/@nuxt/cli/dist/cli-index.js:603
  } catch { }
          ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/tony.hayes/git/trisha/node_modules/@nuxt/cli/dist/cli.js:11:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! trish@1.0.0 dev: `nuxt`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the trish@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tony.hayes/.npm/_logs/2021-12-29T20_31_09_524Z-debug.log
Tonys-MacBook-Pro:trisha tony.hayes$ 

any thoughts?

**Comment by staticdesigner** [comment]
Hi @tonyhayes, this issue occurs when running the project with an older version of Node.js (Node.js < 10) that does not support the ES2019 optional catch binding syntax (`catch { }`).

Since the project has been updated to run on modern versions of Node.js (e.g., Node 16 is specified in the Docker environment), this issue is no longer applicable. I am closing this issue. Thank you!
